### ISSUE TITLE
I am getting following error when using in laravel

### ISSUE THREAD

**Issue by prashantidealittechno** [onfido/api-php-client#1]
Do you know what is missing?
ApiException in /var/www/dev.usercheck.com/vendor/onfido/api-php-client/lib/ApiClient.php line 275: [422] Error connecting to the API (https://api.onfido.com/v2/applicants)

**Comment by Alfreddd** [comment]
Hi @prashantidealittechno , please send us an email at api@onfido.com to help you best. Thanks!
