### ISSUE TITLE
How i can generate the web hook signature from payload  to compare it with  "X-Sha2-Signature",  the document not clear for this point  

### ISSUE THREAD

**Issue by hema3rafa** [onfido/api-php-client#4]

**Comment by Lechus** [comment]
It is not PHP,, but maybe will give you a clue...
https://github.com/onfido/api-python-client/issues/2

**Comment by speix** [comment]
Ok the problem was that the two lines below are not necessary for php (maybe you should mention that). hash_hmac returns lowercase hexits by default.

# Make sure to decode the signature header from hexidecimal before comparing.
# Alternatively, convert the expected signature to hexidecimal.

**Comment by speix** [comment]
In case someone is interested:

```
`# Some kind of middleware`
public function handleWebHookAuth(Request $request, string $token)
{
     # Get header signature value
     $signature_header_hexadecimal = $request->header('x-sha2-signature');

     # Get request body and compress it. A minify function or a regex will do it as well.
     $raw_body = json_encode(json_decode($request->getContent()), JSON_UNESCAPED_SLASHES);

     # Calculate the signature
     $expected_signature = hash_hmac('SHA256', $raw_body, $token);

     # Compare it with timing attack safety
     if (! hash_equals($signature_header_hexadecimal, $expected_signature))
         throw new UnauthorizedException('Unauthenticated request', 401);

     // Forward request
}
```

**Comment by ciaran16** [comment]
Thanks for the feedback @speix, we've changed the guide slightly to indicate it's not always necessary to convert the expected signature.

https://developers.onfido.com/guide/manual-webhook-signature-verification

**Comment by ciaran16** [comment]
I'm going to close this issue as we now have documentation for verifying webhook signatures, but feel free to leave a comment if you have any more feedback.
